# flake8: noqa: F401
from renetti.ws.spiders.sites.atlantis_strength import AtlantisStrengthSpider
from renetti.ws.spiders.sites.eleiko import EleikoSpider
from renetti.ws.spiders.sites.gym_equipment import GymEquipmentSpider
from renetti.ws.spiders.sites.hoist_fitness import HoistFitnessSpider
from renetti.ws.spiders.sites.life_fitness import LifeFitnessSpider
from renetti.ws.spiders.sites.matrix_fitness import MatrixGymSpider
from renetti.ws.spiders.sites.rogue_fitness import RogueFitnessSpider
from renetti.ws.spiders.sites.techno_gym import TechnoGymSpider
from renetti.ws.spiders.sites.uk_gym_equipment import UkGymEquipmentSpider
